
train:
  common:
    use_test_host: true
    omero_group: "cci-staff"

  configs:
    - config:
      name: asdf
      model_save_dir: "train"
      epochs: 300
      patience: 200
      skip_classes: [2, 3]
      datasets: [1,2]
      skip_dataset_creation: true
      #ignore_rois_by_xxx should be considered mutual exclusive! Both are optional though.
      #If any of them is true ROIS matching either name or description from config.py variables will be ignored during training
      #ignore_rois_by_description: true
      ignore_rois_by_name: true


    - config:
      name: train_cells_and_granules_on_most_datasets
      model_save_dir: "cells_and_granules"
      epochs: 300
      patience: 200
      skip_classes: [2, 3]
      datasets: [1159, 1206,1214,  1226, 1305, 1551, 1952, 2152, 2201]
      skip_dataset_creation: false
      omero_group: "Emma-Josefsson-Lab"
      use_test_host: false

      #ignore_rois_by_xxx should be considered mutual exclusive! Both are optional though.
      #If any of them is true ROIS matching either name or description from config.py variables will be ignored during training
      #ignore_rois_by_description: true
      ignore_rois_by_name: true

    - config:
      name: train_cells_and_granules_last
      model_save_dir: "cells_and_granules"
      epochs: 300
      patience: 50
      skip_classes: [2, 3]
      datasets: [1159, 1214, 1226, 1305, 1354, 1551, 1803, 1952, 2152, 2201, 2202, 2251, 2351, 2408, 2451]
      skip_dataset_creation: false
      omero_group: "Emma-Josefsson-Lab"
      use_test_host: false
      #ignore_rois_by_xxx should be considered mutual exclusive! Both are optional though.
      #If any of them is true ROIS matching either name or description from config.py variables will be ignored during training
      #ignore_rois_by_description: true
      ignore_rois_by_name: true


annotate:
  common:
    use_test_host: false
    omero_group: "cci-staff"

  configs:
    - config:
      name: annotate_cells_and_granules
      dataset_id: 2401
      model_dir: "cells_and_granules\\2026-03-04\\11-31\\best.pt"
      filter_border: true
      border_width: 10
      #remove rois: true removes rois matching name OR description from config.py AI_ROI_NAME = "from AI" and AI_ROI_DESCRIPTION = "auto annotated"
      remove_rois: false
      confidence_threshold: 0.0

